name: ArmorStandGUI
version: '${project.version}'
main: me.clayplayer.armorstandgui.ArmorStandGUI
api-version: 1.19
commands:
  armorstandgui:
    description: ArmorStandGUI command
    usage: /<command>